//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICarryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public int ID { get; set; }
        public string descripcionServicio { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> transportador { get; set; }
        public string carga { get; set; }
        public string direccionCague { get; set; }
        public string direccionEntrega { get; set; }
        public Nullable<int> costo { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual transportador transportador1 { get; set; }
    }
}
