//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICarryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transportador()
        {
            this.servicio = new HashSet<servicio>();
        }
    
        public int id { get; set; }
        public Nullable<int> cedula { get; set; }
        public string vehiculo { get; set; }
        public int estado { get; set; }
    
        public virtual persona persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicio> servicio { get; set; }
        public virtual vehiculo vehiculo1 { get; set; }
    }
}
